#!/bin/bash
#
# Copyright (C) 2013    Ian Firns   <firnsy@kororaproject.org>
#                       Chris Smart <csmart@kororaproject.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

USERNAME="firnsy"
HOST="http://localhost:3000"

#
# ADOBE
#
for ARCH in i386 x86_64
do
  PYTHONPATH=./lib-python/ ./rpm-exporter --verbose -u ${USERNAME} --host ${HOST} -p --cachedir=./cache --resource http://linuxdownload.adobe.com/linux/${ARCH}/ --stub adobe --name "Adobe - ${ARCH}" --arch=${ARCH} --version=0
done

#
# GOOGLE
#
for ARCH in i386 x86_64
do
  for APP in chrome talkplugin earth
  do
    PYTHONPATH=./lib-python/ ./rpm-exporter --verbose -u ${USERNAME} --host ${HOST} -p --cachedir=./cache --resource http://dl.google.com/linux/${APP}/rpm/stable/${ARCH}/ --stub google-${APP} --name "Google - ${APP}" --arch=${ARCH} --version=0
  done
done

#
# VIRTUALBOX
#
for RELEASEVER in 18 19
do
  for ARCH in i386 x86_64
  do
    PYTHONPATH=./lib-python/ ./rpm-exporter --verbose -u ${USERNAME} --host ${HOST} -p --cachedir=./cache --resource http://download.virtualbox.org/virtualbox/rpm/fedora/${RELEASEVER}/${ARCH} --stub virtualbox --name "Virtualbox ${RELEASEVER} - ${ARCH}" --arch=${ARCH} --version=0
  done
done

#
# KORORA / FEDORA / RPMFUSION
#
for RELEASEVER in 18 19
do
  for ARCH in i386 x86_64
  do
    PYTHONPATH=./lib-python/ ./rpm-exporter --verbose -u ${USERNAME} --host ${HOST} -p --cachedir=./cache --resource http://dl.kororaproject.org/pub/fedora/linux/releases/${RELEASEVER}/Everythng/${ARCH}/os/ --stub korora --name "Korora ${RELEASEVER} - ${ARCH}" --arch=${ARCH} --version=${RELEASEVER}

    PYTHONPATH=./lib-python/ ./rpm-exporter --verbose -u ${USERNAME} --host ${HOST} -p --cachedir=./cache --resource http://dl.fedoraproject.org/pub/fedora/linux/releases/${RELEASEVER}/Everythng/${ARCH}/os/ --stub fedora --name "Fedora ${RELEASEVER} - ${ARCH}" --arch=${ARCH} --version=${RELEASEVER}

    # fedora-updates
    PYTHONPATH=./lib-python/ ./rpm-exporter --verbose -u ${USERNAME} --host ${HOST} -p --cachedir=./cache --resource http://dl.fedoraproject.org/pub/fedora/linux/updates/${RELEASEVER}/${ARCH}/ --stub fedora-updates --name "Fedora ${RELEASEVER} - ${ARCH} - Updates" --arch=${ARCH} --version=${RELEASEVER}

    # rpmfusion-free
    PYTHONPATH=./lib-python/ ./rpm-exporter --verbose -u ${USERNAME} --host ${HOST} -p --cachedir=./cache --resource http://download1.rpmfusion.org/free/fedora/releases/${RELEASEVER}/Everything/${ARCH}/os/ --stub rpmfusion-free --name "RPM Fusion for Fedora ${RELEASEVER} - ${ARCH} - Free" --arch=${ARCH} --version=${RELEASEVER}

    # rpmfusion-free-updates
    PYTHONPATH=./lib-python/ ./rpm-exporter --verbose -u ${USERNAME} --host ${HOST} -p --cachedir=./cache --resource http://download1.rpmfusion.org/free/fedora/updates/${RELEASEVER}/${ARCH}/ --stub rpmfusion-free-updates --name "RPM Fusion for Fedora ${RELEASEVER} - ${ARCH} - Free - Updates" --arch=${ARCH} --version=${RELEASEVER}

    # rpmfusion-nonfree
    PYTHONPATH=./lib-python/ ./rpm-exporter --verbose -u ${USERNAME} --host ${HOST} -p --cachedir=./cache --resource http://download1.rpmfusion.org/nonfree/fedora/releases/${RELEASEVER}/Everything/${ARCH}/os/ --stub rpmfusion-nonfree --name "RPM Fusion for Fedora ${RELEASEVER} - ${ARCH} - Nonfree" --arch=${ARCH} --version=${RELEASEVER}

    # rpmfusion-nonfree-updates
    PYTHONPATH=./lib-python/ ./rpm-exporter --verbose -u ${USERNAME} --host ${HOST} -p --cachedir=./cache --resource http://download1.rpmfusion.org/nonfree/fedora/updates/${RELEASEVER}/${ARCH}/ --stub rpmfusion-nonfree-updates --name "RPM Fusion for Fedora ${RELEASEVER} - ${ARCH} - Nonfree - Updates" --arch=${ARCH} --version=${RELEASEVER}

  done
done

